// Startdaten — Vokabeln aus den beiden Schulbüchern.
// Diese werden beim ersten Start in den localStorage geladen.
// Luis (und du) könnt eigene Bücher/Vokabeln in der App ergänzen.

const SEED_BOOKS = [
  {
    id: "decouvertes4",
    title: "Découvertes 4",
    lang: "Französisch",
    flag: "🇫🇷",
    units: [
      {
        id: "d4-u1",
        title: "Unité 1 — Au lycée",
        words: [
          { fr: "le lycée", de: "das Gymnasium / die Oberstufe" },
          { fr: "la classe de seconde", de: "die 10. Klasse" },
          { fr: "l'emploi du temps (m.)", de: "der Stundenplan" },
          { fr: "la matière", de: "das (Unterrichts-)Fach" },
          { fr: "réussir (à)", de: "schaffen / Erfolg haben" },
          { fr: "échouer (à)", de: "scheitern / durchfallen" },
          { fr: "l'épreuve (f.)", de: "die Prüfung" },
          { fr: "la note", de: "die Note" },
          { fr: "redoubler", de: "sitzenbleiben / wiederholen" },
          { fr: "s'inscrire", de: "sich einschreiben / anmelden" },
          { fr: "le bulletin", de: "das Zeugnis" },
          { fr: "le conseil de classe", de: "die Klassenkonferenz" },
        ],
      },
      {
        id: "d4-u2",
        title: "Unité 2 — L'engagement",
        words: [
          { fr: "s'engager", de: "sich engagieren / einsetzen" },
          { fr: "le bénévolat", de: "das Ehrenamt / die Freiwilligenarbeit" },
          { fr: "l'association (f.)", de: "der Verein" },
          { fr: "manifester", de: "demonstrieren" },
          { fr: "la manifestation", de: "die Demonstration" },
          { fr: "défendre", de: "verteidigen" },
          { fr: "lutter (contre)", de: "kämpfen (gegen)" },
          { fr: "le droit", de: "das Recht" },
          { fr: "l'égalité (f.)", de: "die Gleichheit" },
          { fr: "la solidarité", de: "die Solidarität" },
          { fr: "convaincre", de: "überzeugen" },
          { fr: "le citoyen / la citoyenne", de: "der Bürger / die Bürgerin" },
        ],
      },
      {
        id: "d4-u3",
        title: "Unité 3 — Le monde du travail",
        words: [
          { fr: "le métier", de: "der Beruf" },
          { fr: "l'entreprise (f.)", de: "das Unternehmen" },
          { fr: "le stage", de: "das Praktikum" },
          { fr: "postuler", de: "sich bewerben" },
          { fr: "l'entretien (m.)", de: "das (Vorstellungs-)Gespräch" },
          { fr: "embaucher", de: "einstellen" },
          { fr: "licencier", de: "entlassen" },
          { fr: "le salaire", de: "das Gehalt / der Lohn" },
          { fr: "le chômage", de: "die Arbeitslosigkeit" },
          { fr: "la formation", de: "die Ausbildung" },
          { fr: "compétent(e)", de: "kompetent / fähig" },
          { fr: "l'avenir (m.)", de: "die Zukunft" },
        ],
      },
    ],
  },
  {
    id: "gateway-b2",
    title: "Gateway to the World B2+",
    lang: "Englisch",
    flag: "🇬🇧",
    units: [
      {
        id: "gw-u1",
        title: "Unit 1 — Identity & belonging",
        words: [
          { fr: "belonging", de: "die Zugehörigkeit" },
          { fr: "to fit in", de: "dazugehören / sich einfügen" },
          { fr: "peer pressure", de: "der Gruppenzwang" },
          { fr: "self-esteem", de: "das Selbstwertgefühl" },
          { fr: "to stand out", de: "auffallen / herausstechen" },
          { fr: "heritage", de: "das (kulturelle) Erbe" },
          { fr: "upbringing", de: "die Erziehung" },
          { fr: "to embrace", de: "annehmen / sich zu eigen machen" },
          { fr: "prejudice", de: "das Vorurteil" },
          { fr: "to relate to", de: "sich identifizieren mit" },
          { fr: "outsider", de: "der Außenseiter" },
          { fr: "mindset", de: "die Denkweise / Einstellung" },
        ],
      },
      {
        id: "gw-u2",
        title: "Unit 2 — A changing world",
        words: [
          { fr: "sustainability", de: "die Nachhaltigkeit" },
          { fr: "carbon footprint", de: "der CO₂-Fußabdruck" },
          { fr: "renewable", de: "erneuerbar" },
          { fr: "to tackle", de: "angehen / bewältigen" },
          { fr: "scarce", de: "knapp / rar" },
          { fr: "to thrive", de: "gedeihen / florieren" },
          { fr: "consumption", de: "der Verbrauch / Konsum" },
          { fr: "awareness", de: "das Bewusstsein" },
          { fr: "to mitigate", de: "abmildern / verringern" },
          { fr: "drought", de: "die Dürre" },
          { fr: "to phase out", de: "auslaufen lassen / abschaffen" },
          { fr: "depletion", de: "die Erschöpfung (von Ressourcen)" },
        ],
      },
      {
        id: "gw-u3",
        title: "Unit 3 — Media & technology",
        words: [
          { fr: "to scroll", de: "scrollen / blättern" },
          { fr: "misinformation", de: "die Falschinformation" },
          { fr: "reliable", de: "zuverlässig" },
          { fr: "biased", de: "voreingenommen / parteiisch" },
          { fr: "to verify", de: "überprüfen / bestätigen" },
          { fr: "privacy", de: "die Privatsphäre" },
          { fr: "surveillance", de: "die Überwachung" },
          { fr: "addictive", de: "süchtig machend" },
          { fr: "to disconnect", de: "abschalten / offline gehen" },
          { fr: "echo chamber", de: "die Echokammer" },
          { fr: "to go viral", de: "viral gehen" },
          { fr: "screen time", de: "die Bildschirmzeit" },
        ],
      },
      {
        id: "gw-u5a",
        title: "Unit 5 — Crime & law (A)",
        words: [
          { fr: "sustainable", de: "nachhaltig" },
          { fr: "synthetic biology", de: "synthetische Biologie" },
          { fr: "tenacity", de: "die Hartnäckigkeit" },
          { fr: "trait", de: "die Eigenschaft" },
          { fr: "worldwide", de: "weltweit" },
          { fr: "worst-case scenario", de: "der schlimmste Fall" },
          { fr: "worthwhile", de: "lohnend" },
          { fr: "a number of", de: "eine Reihe von" },
          { fr: "to acquit someone of charges", de: "jemanden freisprechen" },
          { fr: "additionally", de: "zusätzlich" },
          { fr: "and yet", de: "und trotzdem" },
          { fr: "anti-establishment", de: "gegen das Establishment" },
          { fr: "to arise", de: "aufkommen / entstehen" },
          { fr: "a touch of something", de: "ein Hauch von etwas" },
          { fr: "to ban someone from", de: "ein Verbot gegen jemanden verhängen" },
          { fr: "basis", de: "die Grundlage" },
          { fr: "body cam", de: "die Überwachungskamera (am Körper)" },
          { fr: "bogus", de: "fälschlich / gefälscht" },
          { fr: "by means of", de: "mittels" },
          { fr: "cash strapped and resources tight", de: "knappe Kassen und geringe Ressourcen" },
          { fr: "charismatic", de: "charismatisch" },
          { fr: "civilised", de: "zivilisiert" },
          { fr: "claim", de: "die Behauptung" },
          { fr: "to clog", de: "verstopfen" },
          { fr: "to collaborate with", de: "zusammenarbeiten mit" },
          { fr: "to come into force", de: "in Kraft treten" },
          { fr: "constitutional", de: "verfassungsgemäß" },
          { fr: "court", de: "das Gericht" },
          { fr: "CCTV", de: "die Videoüberwachung (CCTV)" },
          { fr: "designated / non-designated", de: "spezifisch / nicht spezifisch (ausgewiesen)" },
        ],
      },
      {
        id: "gw-u5b",
        title: "Unit 5 — Crime & law (B)",
        words: [
          { fr: "to deter", de: "abhalten / abschrecken" },
          { fr: "discrimination", de: "die Diskriminierung" },
          { fr: "discriminatory", de: "diskriminierend" },
          { fr: "disorderly conduct", de: "ordnungswidriges Verhalten" },
          { fr: "disturbance", de: "die Störung" },
          { fr: "do community service", de: "Arbeit zum Gemeinwohl verrichten" },
          { fr: "editorial", de: "der Leitartikel" },
          { fr: "to enforce", de: "durchsetzen" },
          { fr: "facial recognition", de: "die Gesichtserkennung" },
          { fr: "to harass", de: "bedrängen / belästigen" },
          { fr: "highly", de: "sehr / höchst" },
          { fr: "immaturity", de: "die Unreife" },
          { fr: "to impose a curfew", de: "eine Ausgangssperre verhängen" },
          { fr: "in a bid to", de: "in der Absicht" },
          { fr: "in addition to", de: "zusätzlich zu" },
          { fr: "in aid of", de: "als Hilfe für" },
          { fr: "in favour of", de: "Befürworter/in sein" },
          { fr: "in order to", de: "um zu" },
          { fr: "in response to", de: "als Reaktion auf" },
          { fr: "in the process of", de: "dabei sein (etwas zu tun)" },
          { fr: "in/out of touch with", de: "(nicht) auf dem Laufenden sein" },
          { fr: "indeed", de: "in der Tat" },
          { fr: "to issue someone with a(n) (on-the-spot) fine", de: "jemanden (an Ort und Stelle) mit einer Strafe belegen" },
          { fr: "to judge", de: "verurteilen" },
          { fr: "law-abiding", de: "gesetzestreu" },
          { fr: "littering", de: "das Vermüllen / Wegwerfen von Müll" },
          { fr: "to make a formal apology", de: "sich formell entschuldigen" },
          { fr: "to make a prank/hoax call", de: "einen Scherz-/Falschanruf tätigen" },
          { fr: "matter", de: "die Angelegenheit / Sache" },
          { fr: "merely", de: "nur / bloß" },
          { fr: "mindlessly", de: "unbedacht / gedankenlos" },
          { fr: "nuisance", de: "die Belästigung / das Ärgernis" },
          { fr: "numerous", de: "zahlreich" },
          { fr: "occasionally", de: "gelegentlich" },
          { fr: "on account of", de: "aufgrund von" },
          { fr: "on behalf of", de: "im Namen von" },
          { fr: "on the strength of", de: "daraufhin / gestützt auf" },
          { fr: "on the verge of (doing something)", de: "drauf und dran sein (etwas zu tun)" },
          { fr: "one-off / repeated shoplifting", de: "einmaliger / wiederholter Ladendiebstahl" },
          { fr: "ordinance", de: "die Verordnung" },
          { fr: "parking ticket", de: "der Strafzettel" },
          { fr: "to pass (a law)", de: "(ein Gesetz) verabschieden" },
          { fr: "penalty", de: "die Strafe" },
          { fr: "to precede", de: "vorausgehen" },
          { fr: "to prosecute", de: "strafrechtlich verfolgen" },
          { fr: "prosecution", de: "die Strafverfolgung" },
          { fr: "to receive a suspended sentence", de: "eine Bewährungsstrafe bekommen" },
          { fr: "register", de: "der Wortschatz / das Sprachregister" },
          { fr: "to sacrifice", de: "das Opfer / opfern" },
          { fr: "self-determination", de: "die Selbstbestimmung" },
          { fr: "to settle a fine", de: "eine Strafe bezahlen" },
          { fr: "several", de: "mehrere" },
          { fr: "sleep disorder", de: "die Schlafstörung" },
          { fr: "social worker", de: "der/die Sozialarbeiter/in" },
          { fr: "to supervise", de: "überwachen / beaufsichtigen" },
          { fr: "synonym", de: "das Synonym" },
          { fr: "the vast majority of", de: "die überwiegende Mehrheit" },
          { fr: "to undertake", de: "durchführen / unternehmen" },
          { fr: "undesirable", de: "unerwünscht" },
          { fr: "valid", de: "gültig" },
          { fr: "to validate", de: "entwerten / validieren" },
          { fr: "vandalism", de: "der Vandalismus" },
          { fr: "vulnerability", de: "die Verletzbarkeit" },
        ],
      },
    ],
  },
];
