// Startdaten — Vokabeln aus den beiden Schulbüchern.
// Diese werden beim ersten Start in den localStorage geladen.
// Luis (und du) könnt eigene Bücher/Vokabeln in der App ergänzen.

const SEED_BOOKS = [
  {
    id: "decouvertes4",
    title: "Découvertes 4",
    lang: "Französisch",
    flag: "🇫🇷",
    units: [
      {
        id: "d4-u1",
        title: "Unité 1 — Au lycée",
        words: [
          { fr: "le lycée", de: "das Gymnasium / die Oberstufe" },
          { fr: "la classe de seconde", de: "die 10. Klasse" },
          { fr: "l'emploi du temps (m.)", de: "der Stundenplan" },
          { fr: "la matière", de: "das (Unterrichts-)Fach" },
          { fr: "réussir (à)", de: "schaffen / Erfolg haben" },
          { fr: "échouer (à)", de: "scheitern / durchfallen" },
          { fr: "l'épreuve (f.)", de: "die Prüfung" },
          { fr: "la note", de: "die Note" },
          { fr: "redoubler", de: "sitzenbleiben / wiederholen" },
          { fr: "s'inscrire", de: "sich einschreiben / anmelden" },
          { fr: "le bulletin", de: "das Zeugnis" },
          { fr: "le conseil de classe", de: "die Klassenkonferenz" },
        ],
      },
      {
        id: "d4-u2",
        title: "Unité 2 — L'engagement",
        words: [
          { fr: "s'engager", de: "sich engagieren / einsetzen" },
          { fr: "le bénévolat", de: "das Ehrenamt / die Freiwilligenarbeit" },
          { fr: "l'association (f.)", de: "der Verein" },
          { fr: "manifester", de: "demonstrieren" },
          { fr: "la manifestation", de: "die Demonstration" },
          { fr: "défendre", de: "verteidigen" },
          { fr: "lutter (contre)", de: "kämpfen (gegen)" },
          { fr: "le droit", de: "das Recht" },
          { fr: "l'égalité (f.)", de: "die Gleichheit" },
          { fr: "la solidarité", de: "die Solidarität" },
          { fr: "convaincre", de: "überzeugen" },
          { fr: "le citoyen / la citoyenne", de: "der Bürger / die Bürgerin" },
        ],
      },
      {
        id: "d4-u3",
        title: "Unité 3 — Le monde du travail",
        words: [
          { fr: "le métier", de: "der Beruf" },
          { fr: "l'entreprise (f.)", de: "das Unternehmen" },
          { fr: "le stage", de: "das Praktikum" },
          { fr: "postuler", de: "sich bewerben" },
          { fr: "l'entretien (m.)", de: "das (Vorstellungs-)Gespräch" },
          { fr: "embaucher", de: "einstellen" },
          { fr: "licencier", de: "entlassen" },
          { fr: "le salaire", de: "das Gehalt / der Lohn" },
          { fr: "le chômage", de: "die Arbeitslosigkeit" },
          { fr: "la formation", de: "die Ausbildung" },
          { fr: "compétent(e)", de: "kompetent / fähig" },
          { fr: "l'avenir (m.)", de: "die Zukunft" },
        ],
      },
    ],
  },
  {
    id: "gateway-b2",
    title: "Gateway to the World B2+",
    lang: "Englisch",
    flag: "🇬🇧",
    units: [
      {
        id: "gw-u1",
        title: "Unit 1 — Identity & belonging",
        words: [
          { fr: "belonging", de: "die Zugehörigkeit" },
          { fr: "to fit in", de: "dazugehören / sich einfügen" },
          { fr: "peer pressure", de: "der Gruppenzwang" },
          { fr: "self-esteem", de: "das Selbstwertgefühl" },
          { fr: "to stand out", de: "auffallen / herausstechen" },
          { fr: "heritage", de: "das (kulturelle) Erbe" },
          { fr: "upbringing", de: "die Erziehung" },
          { fr: "to embrace", de: "annehmen / sich zu eigen machen" },
          { fr: "prejudice", de: "das Vorurteil" },
          { fr: "to relate to", de: "sich identifizieren mit" },
          { fr: "outsider", de: "der Außenseiter" },
          { fr: "mindset", de: "die Denkweise / Einstellung" },
        ],
      },
      {
        id: "gw-u2",
        title: "Unit 2 — A changing world",
        words: [
          { fr: "sustainability", de: "die Nachhaltigkeit" },
          { fr: "carbon footprint", de: "der CO₂-Fußabdruck" },
          { fr: "renewable", de: "erneuerbar" },
          { fr: "to tackle", de: "angehen / bewältigen" },
          { fr: "scarce", de: "knapp / rar" },
          { fr: "to thrive", de: "gedeihen / florieren" },
          { fr: "consumption", de: "der Verbrauch / Konsum" },
          { fr: "awareness", de: "das Bewusstsein" },
          { fr: "to mitigate", de: "abmildern / verringern" },
          { fr: "drought", de: "die Dürre" },
          { fr: "to phase out", de: "auslaufen lassen / abschaffen" },
          { fr: "depletion", de: "die Erschöpfung (von Ressourcen)" },
        ],
      },
      {
        id: "gw-u3",
        title: "Unit 3 — Media & technology",
        words: [
          { fr: "to scroll", de: "scrollen / blättern" },
          { fr: "misinformation", de: "die Falschinformation" },
          { fr: "reliable", de: "zuverlässig" },
          { fr: "biased", de: "voreingenommen / parteiisch" },
          { fr: "to verify", de: "überprüfen / bestätigen" },
          { fr: "privacy", de: "die Privatsphäre" },
          { fr: "surveillance", de: "die Überwachung" },
          { fr: "addictive", de: "süchtig machend" },
          { fr: "to disconnect", de: "abschalten / offline gehen" },
          { fr: "echo chamber", de: "die Echokammer" },
          { fr: "to go viral", de: "viral gehen" },
          { fr: "screen time", de: "die Bildschirmzeit" },
        ],
      },
    ],
  },
];
